-- Tabel super_admin
CREATE TABLE super_admin (
    id INT AUTO_INCREMENT PRIMARY KEY,      -- ID super admin
    username VARCHAR(50) NOT NULL UNIQUE,   -- Username super admin
    password VARCHAR(255) NOT NULL,         -- Password super admin (hashed)
    nama_admin VARCHAR(100) NOT NULL     -- Nama lengkap super admin
);

-- Insert data ke tabel super_admin
INSERT INTO super_admin (username, password, nama_admin) VALUES
('superadmin1', '12345', 'Super Admin 1'),
('superadmin2', '12345', 'Super Admin 2'),
('superadmin3', '12345', 'Super Admin 3');


CREATE TABLE fakultas (
    id INT AUTO_INCREMENT PRIMARY KEY,       -- ID fakultas
    nama_fakultas VARCHAR(100) NOT NULL      -- Nama fakultas
);

-- Insert data ke tabel fakultas
INSERT INTO fakultas (nama_fakultas) VALUES 
('DAKWAH DAN ILMU KOMUNIKASI'),
('EKONOMI DAN ILMU SOSIAL'),
('PASCASARJANA'),
('PERTANIAN DAN PETERNAKAN'),
('PSIKOLOGI'),
('SAINS DAN TEKNOLOGI'),
('SYARIAH DAN ILMU HUKUM'),
('TARBIYAH DAN KEGURUAN'),
('USHULUDDIN');

CREATE TABLE admin_fakultas (
    id INT AUTO_INCREMENT PRIMARY KEY,       -- ID admin fakultas
    fakultas_id INT NOT NULL,                -- Referensi ke tabel fakultas
    username VARCHAR(50) NOT NULL UNIQUE,    -- Username admin fakultas
    password VARCHAR(255) NOT NULL,          -- Password admin fakultas (hashed)
    nama_admin_fakultas VARCHAR(100) NOT NULL      -- Nama lengkap admin fakultas
);

-- Insert data ke tabel admin_fakultas sesuai dengan fakultas yang ada
INSERT INTO admin_fakultas (fakultas_id, username, password, nama_admin_fakultas) VALUES
(1, 'admin_dakwah', '12345', 'Admin Dakwah Dan Ilmu Komunikasi'),
(2, 'admin_ekonomi', '12345', 'Admin Ekonomi Dan Ilmu Sosial'),
(3, 'admin_pascasarjana', '12345', 'Admin Pascasarjana'),
(4, 'admin_pertanian', '12345', 'Admin Pertanian Dan Peternakan'),
(5, 'admin_psikologi', '12345', 'Admin Psikologi'),
(6, 'admin_sainstek', '12345', 'Admin Sains Dan Teknologi'),
(7, 'admin_syariah', '12345', 'Admin Syariah Dan Ilmu Hukum'),
(8, 'admin_tarbiyah', '12345', 'Admin Tarbiyah Dan Keguruan'),
(9, 'admin_ushuluddin', '12345', 'Admin Ushuluddin');


CREATE TABLE prodi (
    id INT AUTO_INCREMENT PRIMARY KEY,       -- ID program studi
    nama_prodi VARCHAR(100) NOT NULL,        -- Nama program studi
    fakultas_id INT NOT NULL,                -- Relasi ke fakultas
    FOREIGN KEY (fakultas_id) REFERENCES fakultas(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Insert data ke tabel prodi
INSERT INTO prodi (nama_prodi, fakultas_id) VALUES 

-- Fakultas Dakwah dan Ilmu Komunikasi
('Bimbingan dan Konseling Islam', 1),
('Ilmu Komunikasi', 1),
('Manajemen Dakwah', 1),
('Pengembangan Masyarakat Islam', 1),

-- Fakultas Ekonomi dan Ilmu Sosial
('Administrasi Negara S1', 2),
('Akuntansi S1', 2),
('Diploma III Administrasi Perpajakan', 2),
('Diploma III Akuntansi', 2),
('Diploma III Manajemen Perusahaan', 2),
('Manajemen S1', 2),

-- Fakultas Pascasarjana
('Ekonomi Islam (EI) - Magister', 3),
('Hukum Islam (HI) - Doktor', 3),
('Hukum Islam (HI) - Magister', 3),
('Manajemen Pendidikan Islam (MPI) - Magister', 3),
('Pendidikan Agama Islam (PAI) - Doktor', 3),
('Pendidikan Agama Islam (PAI) - Magister', 3),
('Pendidikan Bahasa Arab (PBA) - Magister', 3),
('Pendidikan Bahasa Inggris (PBI) - Magister', 3),
('Tafsir Hadis (TH) - Magister', 3),

-- Fakultas Pertanian dan Peternakan
('Gizi', 4),
('Jurusan Argoteknologi', 4),
('Jurusan Peternakan', 4),

-- Fakultas Psikologi
('S1 Psikologi', 5),
('S2 Psikologi', 5),

-- Fakultas Sains dan Teknologi
('Matematika Terapan', 6),
('Sistem Informasi', 6),
('Teknik Elektro', 6),
('Teknik Industri', 6),
('Teknik Informatika', 6),

-- Fakultas Syariah dan Ilmu Hukum
('Ahwal Al-Syakhshiyyah', 7),
('DIII Perbankan Syariah', 7),
('Ekonomi Islam', 7),
('Ilmu Hukum', 7),
('Jinayah Siyasah', 7),
('Muammalah', 7),
('Perbandingan Mazhab dan Hukum', 7),

-- Fakultas Tarbiyah dan Keguruan
('Jurusan Kependidikan Islam', 8),
('Jurusan Pendidikan Bahasa Inggris', 8),
('Pendidikan Agama Islam', 8),
('Pendidikan Bahasa Arab', 8),
('Pendidikan Bahasa Indonesia', 8),
('Pendidikan Geografi', 8),
('Pendidikan Guru Madrasah Ibtidaiyah', 8),
('Pendidikan IPS Ekonomi', 8),
('Pendidikan Kimia', 8),
('Pendidikan Matematika', 8),
('Tadris IPA', 8),

-- Fakultas Ushuluddin
('Ilmu Hadis', 9),
('Jurusan Aqidah dan Filsafat', 9),
('Jurusan Perbandingan Agama', 9),
('Jurusan Tafsir Hadits', 9);


CREATE TABLE alumni(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nama VARCHAR(100) NOT NULL,
    angkatan VARCHAR(2) NOT NULL,
    prodi_id INT(100) NOT NULL,
    ipk VARCHAR(100) NOT NULL,
    lulus DATE NOT NULL,
    nim VARCHAR(12) NOT NULL,
    FOREIGN KEY (prodi_id) REFERENCES prodi(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO alumni (nama, angkatan, prodi_id, ipk, lulus, nim, password) VALUES
('Ali', 2020, 26, 3.75, '2023-07-20', '12050115011'),
('Siti', 2019, 27, 3.80, '2023-06-15', '12050115012'),
('Muhammad Rizal Fadhli', 2020, 29, 3.80, '2024-09-15', '12050113626');

CREATE TABLE provinsi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_provinsi VARCHAR(100) NOT NULL
);

INSERT INTO provinsi (nama_provinsi) VALUES
('Aceh'), ('Bali'), ('Banten'), ('Bengkulu'), ('Bangka Belitung'), 
('DI Yogyakarta'), ('DKI Jakarta'), ('Gorontalo'), ('Jambi'), 
('Jawa Barat'), ('Jawa Tengah'), ('Jawa Timur'), ('Kalimantan Barat'), 
('Kalimantan Selatan'), ('Kalimantan Tengah'), ('Kalimantan Timur'), 
('Kalimantan Utara'), ('Kepulauan Bangka Belitung'), ('Kepulauan Riau'), 
('Lampung'), ('Maluku'), ('Maluku Utara'), ('Nusa Tenggara Barat'), 
('Nusa Tenggara Timur'), ('Papua'), ('Papua Barat'), ('Papua Barat Daya'), 
('Papua Pegunungan'), ('Papua Selatan'), ('Papua Tengah'), ('Riau'), 
('Sumatera Barat'), ('Sumatera Selatan'), ('Sumatera Utara'), 
('Sulawesi Barat'), ('Sulawesi Selatan'), ('Sulawesi Tengah'), 
('Sulawesi Tenggara'), ('Sulawesi Utara');


CREATE TABLE kabupaten (
    id INT AUTO_INCREMENT PRIMARY KEY,
    provinsi_id INT NOT NULL,
    nama_kabupaten VARCHAR(100) NOT NULL,
    FOREIGN KEY (provinsi_id) REFERENCES provinsi(id) ON DELETE CASCADE
);

INSERT INTO kabupaten (provinsi_id, nama_kabupaten) VALUES
-- 1. Aceh
(1,'Kabupaten Aceh Barat'),
(1,'Kabupaten Aceh Barat Daya'),
(1,'Kabupaten Aceh Besar'),
(1,'Kabupaten Aceh Jaya'),
(1,'Kabupaten Aceh Selatan'),
(1,'Kabupaten Aceh Singkil'),
(1,'Kabupaten Aceh Tamiang'),
(1,'Kabupaten Aceh Tengah'),
(1,'Kabupaten Aceh Tenggara'),
(1,'Kabupaten Aceh Timur'),
(1,'Kabupaten Aceh Utara'),
(1,'Kabupaten Bener Meriah'),
(1,'Kabupaten Bireuen'),
(1,'Kabupaten Gayo Lues'),
(1,'Kabupaten Nagan Raya'),
(1,'Kabupaten Pidie'),
(1,'Kabupaten Pidie Jaya'),
(1,'Kabupaten Simeulue'),
(1,'Kota Banda Aceh'),
(1,'Kota Langsa'),
(1,'Kota Lhokseumawe'),
(1,'Kota Sabang'),
(1,'Kota Subulussalam'),

-- 2. Bali
(2,'Kabupaten Badung'),
(2,'Kabupaten Bangli'),
(2,'Kabupaten Buleleng'),
(2,'Kabupaten Gianyar'),
(2,'Kabupaten Jembrana'),
(2,'Kabupaten Karangasem'),
(2,'Kabupaten Klungkung'),
(2,'Kabupaten Tabanan'),
(2,'Kota Denpasar'),

-- 3. Bangka Belitung
(3,'Kabupaten Bangka'),
(3,'Kabupaten Bangka Barat'),
(3,'Kabupaten Bangka Selatan'),
(3,'Kabupaten Bangka Tengah'),
(3,'Kabupaten Belitung'),
(3,'Kabupaten Belitung Timur'),
(3,'Kota Pangkal Pinang'),

-- 4. Banten
(4,'Kabupaten Lebak'),
(4,'Kabupaten Pandeglang'),
(4,'Kabupaten Serang'),
(4,'Kabupaten Tangerang'),
(4,'Kota Cilegon'),
(4,'Kota Serang'),
(4,'Kota Tangerang'),
(4,'Kota Tangerang Selatan'),

-- 5. Bengkulu
(5,'Kabupaten Bengkulu Selatan'),
(5,'Kabupaten Bengkulu Tengah'),
(5,'Kabupaten Bengkulu Utara'),
(5,'Kabupaten Kaur'),
(5,'Kabupaten Kepahiang'),
(5,'Kabupaten Lebong'),
(5,'Kabupaten Mukomuko'),
(5,'Kabupaten Rejang Lebong'),
(5,'Kabupaten Seluma'),
(5,'Kota Bengkulu'),

-- 6. DI Yogyakarta
(6, 'Kabupaten Bantul'),
(6, 'Kabupaten Gunungkidul'),
(6, 'Kabupaten Kulon Progo'),
(6, 'Kabupaten Sleman'),
(6, 'Kota Yogyakarta'),

-- 7. DKI Jakarta
(7, 'Kota Administrasi Kepulauan Seribu'),
(7, 'Kota Jakarta Barat'),
(7, 'Kota Jakarta Pusat'),
(7, 'Kota Jakarta Selatan'),
(7, 'Kota Jakarta Timur'),
(7, 'Kota Jakarta Utara'),


-- 8. Gorontalo
(8, 'Kabupaten Bone Bolango'),
(8, 'Kabupaten Boalemo'),
(8, 'Kabupaten Gorontalo'),
(8, 'Kabupaten Gorontalo Utara'),
(8, 'Kabupaten Pohuwato'),
(8, 'Kota Gorontalo'),

-- 9. Jambi
(1,'Kabupaten Batanghari'),
(1,'Kabupaten Bungo'),
(1,'Kabupaten Kerinci'),
(1,'Kabupaten Merangin'),
(1,'Kabupaten Muaro Jambi'),
(1,'Kabupaten Sarolangun'),
(1,'Kabupaten Tanjung Jabung Barat'),
(1,'Kabupaten Tanjung Jabung Timur'),
(1,'Kabupaten Tebo'),
(1,'Kota Jambi'),
(1,'Kota Sungai Penuh'),

-- 10. Jawa Barat
(10, 'Kabupaten Bandung'),
(10, 'Kabupaten Bandung Barat'),
(10, 'Kabupaten Bekasi'),
(10, 'Kabupaten Bogor'),
(10, 'Kabupaten Ciamis'),
(10, 'Kabupaten Cianjur'),
(10, 'Kabupaten Cirebon'),
(10, 'Kabupaten Garut'),
(10, 'Kabupaten Indramayu'),
(10, 'Kabupaten Karawang'),
(10, 'Kabupaten Kuningan'),
(10, 'Kabupaten Majalengka'),
(10, 'Kabupaten Pangandaran'),
(10, 'Kabupaten Purwakarta'),
(10, 'Kabupaten Subang'),
(10, 'Kabupaten Sukabumi'),
(10, 'Kabupaten Sumedang'),
(10, 'Kabupaten Tasikmalaya'),
(10, 'Kota Bandung'),
(10, 'Kota Banjar'),
(10, 'Kota Bekasi'),
(10, 'Kota Bogor'),
(10, 'Kota Cimahi'),
(10, 'Kota Cirebon'),
(10, 'Kota Depok'),
(10, 'Kota Sukabumi'),
(10, 'Kota Tasikmalaya'),

-- 11. Jawa Tengah
(11,'Kabupaten Banjarnegara'),
(11,'Kabupaten Banyumas'),
(11,'Kabupaten Batang'),
(11,'Kabupaten Blora'),
(11,'Kabupaten Boyolali'),
(11,'Kabupaten Brebes'),
(11,'Kabupaten Cilacap'),
(11,'Kabupaten Demak'),
(11,'Kabupaten Grobogan'),
(11,'Kabupaten Jepara'),
(11,'Kabupaten Karanganyar'),
(11,'Kabupaten Kebumen'),
(11,'Kabupaten Kendal'),
(11,'Kabupaten Klaten'),
(11,'Kabupaten Kudus'),
(11,'Kabupaten Magelang'),
(11,'Kabupaten Pati'),
(11,'Kabupaten Pekalongan'),
(11,'Kabupaten Pemalang'),
(11,'Kabupaten Purworejo'),
(11,'Kabupaten Semarang'),
(11,'Kabupaten Sragen'),
(11,'Kabupaten Sukoharjo'),
(11,'Kabupaten Tegal'),
(11,'Kabupaten Temanggung'),
(11,'Kabupaten Wonogiri'),
(11,'Kabupaten Wonosobo'),
(11,'Kota Magelang'),
(11,'Kota Pekalongan'),
(11,'Kota Semarang'),
(11,'Kota Surakarta'),
(11,'Kota Tegal'),

-- 12. Jawa Timur
(12,'Kabupaten Bangkalan'),
(12,'Kabupaten Banyuwangi'),
(12,'Kabupaten Blitar'),
(12,'Kabupaten Bojonegoro'),
(12,'Kabupaten Bondowoso'),
(12,'Kabupaten Gresik'),
(12,'Kabupaten Jember'),
(12,'Kabupaten Jombang'),
(12,'Kabupaten Kediri'),
(12,'Kabupaten Lamongan'),
(12,'Kabupaten Lumajang'),
(12,'Kabupaten Madiun'),
(12,'Kabupaten Magetan'),
(12,'Kabupaten Malang'),
(12,'Kabupaten Mojokerto'),
(12,'Kabupaten Nganjuk'),
(12,'Kabupaten Ngawi'),
(12,'Kabupaten Pacitan'),
(12,'Kabupaten Pamekasan'),
(12,'Kabupaten Pasuruan'),
(12,'Kabupaten Ponorogo'),
(12,'Kabupaten Probolinggo'),
(12,'Kabupaten Sampang'),
(12,'Kabupaten Sidoarjo'),
(12,'Kabupaten Situbondo'),
(12,'Kabupaten Sumenep'),
(12,'Kabupaten Trenggalek'),
(12,'Kabupaten Tuban'),
(12,'Kabupaten Tulungagung'),
(12,'Kota Batu'),
(12,'Kota Blitar'),
(12,'Kota Kediri'),
(12,'Kota Madiun'),
(12,'Kota Malang'),
(12,'Kota Mojokerto'),
(12,'Kota Pasuruan'),
(12,'Kota Probolinggo'),
(12,'Kota Surabaya'),

-- 13. Kalimantan Barat
(13, 'Kabupaten Bengkayang'),
(13, 'Kabupaten Kapuas Hulu'),
(13, 'Kabupaten Kayong Utara'),
(13, 'Kabupaten Ketapang'),
(13, 'Kabupaten Kubu Raya'),
(13, 'Kabupaten Landak'),
(13, 'Kabupaten Melawi'),
(13, 'Kabupaten Mempawah'),
(13, 'Kabupaten Sambas'),
(13, 'Kabupaten Sanggau'),
(13, 'Kabupaten Sekadau'),
(13, 'Kabupaten Sintang'),
(13, 'Kota Pontianak'),
(13, 'Kota Singkawang'),

-- 14. Kalimantan Selatan
(14, 'Kabupaten Balangan'),
(14, 'Kabupaten Banjar'),
(14, 'Kabupaten Barito Kuala'),
(14, 'Kabupaten Hulu Sungai Selatan'),
(14, 'Kabupaten Hulu Sungai Tengah'),
(14, 'Kabupaten Hulu Sungai Utara'),
(14, 'Kabupaten Kandangan'),
(14, 'Kabupaten Kotabaru'),
(14, 'Kabupaten Tabalong'),
(14, 'Kabupaten Tanah Bumbu'),
(14, 'Kabupaten Tanah Laut'),
(14, 'Kota Banjarbaru'),
(14, 'Kota Banjarmasin'),

-- 15. Kalimantan Tengah
(15,'Kabupaten Barito Barat'),
(15,'Kabupaten Barito Selatan'),
(15,'Kabupaten Barito Timur'),
(15,'Kabupaten Barito Utara'),
(15,'Kabupaten Gunung Mas'),
(15,'Kabupaten Kapuas'),
(15,'Kabupaten Katingan'),
(15,'Kabupaten Kotawaringin Barat'),
(15,'Kabupaten Kotawaringin Timur'),
(15,'Kabupaten Lamandau'),
(15,'Kabupaten Murung Raya'),
(15,'Kabupaten Pulang Pisau'),
(15,'Kabupaten Seruyan'),
(15,'Kabupaten Sukamara'),
(15,'Kota Palangkaraya'),

-- 16. Kalimantan Timur
(16,'Kabupaten Berau'),
(16,'Kabupaten Kutai Barat'),
(16,'Kabupaten Kutai Kartanegara'),
(16,'Kabupaten Kutai Timur'),
(16,'Kabupaten Paser'),
(16,'Kabupaten Penajam Paser Utara'),
(16,'Kabupaten Mahakam Ulu'),
(16,'Kota Balikpapan'),
(16,'Kota Bontang'),
(16,'Kota Samarinda'),

-- 17. Kalimantan Utara
(17,'Kabupaten Bulungan'),
(17,'Kabupaten Malinau'),
(17,'Kabupaten Nunukan'),
(17,'Kabupaten Tana Tidung'),
(17,'Kota Tarakan'),

-- 18. Kepulauan Riau
(18,'Kabupaten Bintan'),
(18,'Kabupaten Karimun'),
(18,'Kabupaten Kepulauan Anambas'),
(18,'Kabupaten Lingga'),
(18,'Kabupaten Natuna'),
(18,'Kota Batam'),
(18,'Kota Tanjung Pinang'),

-- 19. Lampung
(19,'Kabupaten Lampung Barat'),
(19,'Kabupaten Lampung Selatan'),
(19,'Kabupaten Lampung Tengah'),
(19,'Kabupaten Lampung Timur'),
(19,'Kabupaten Lampung Utara'),
(19,'Kabupaten Mesuji'),
(19,'Kabupaten Pesawaran'),
(19,'Kabupaten Pesisir Barat'),
(19,'Kabupaten Pringsewu'),
(19,'Kabupaten Tanggamus'),
(19,'Kabupaten Tulang Bawang'),
(19,'Kabupaten Tulang Bawang Barat'),
(19,'Kabupaten Way Kanan'),
(19,'Kota Bandar Lampung'),
(19,'Kota Metro'),

-- 20. Maluku
(20, 'Kabupaten Buru'),
(20, 'Kabupaten Buru Selatan'),
(20, 'Kabupaten Kepulauan Aru'),
(20, 'Kabupaten Kepulauan Tanimbar'),
(20, 'Kabupaten Maluku Barat Daya'),
(20, 'Kabupaten Maluku Tengah'),
(20, 'Kabupaten Maluku Tenggara'),
(20, 'Kabupaten Seram Bagian Barat'),
(20, 'Kabupaten Seram Bagian Timur'),
(20, 'Kota Ambon'),
(20, 'Kota Tual'),

-- 21. Maluku Utara
(21, 'Kabupaten Halmahera Barat'),
(21, 'Kabupaten Halmahera Selatan'),
(21, 'Kabupaten Halmahera Tengah'),
(21, 'Kabupaten Halmahera Timur'),
(21, 'Kabupaten Halmahera Utara'),
(21, 'Kabupaten Kepulauan Sula'),
(21, 'Kabupaten Pulau Morotai'),
(21, 'Kabupaten Pulau Taliabu'),
(21, 'Kota Tidore Kepulauan'),
(21, 'Kota Ternate'),

-- 22. Nusa Tenggara Barat
(22,'Kabupaten Bima'),
(22,'Kabupaten Dompu'),
(22,'Kabupaten Lombok Barat'),
(22,'Kabupaten Lombok Tengah'),
(22,'Kabupaten Lombok Timur'),
(22,'Kabupaten Lombok Utara'),
(22,'Kabupaten Sumbawa'),
(22,'Kabupaten Sumbawa Barat'),
(22,'Kota Bima'),
(22,'Kota Mataram'),

-- 23. Nusa Tenggara Timur
(23,'Kabupaten Alor'),
(23,'Kabupaten Belu'),
(23,'Kabupaten Ende'),
(23,'Kabupaten Flores Timur'),
(23,'Kabupaten Kupang'),
(23,'Kabupaten Lembata'),
(23,'Kabupaten Manggarai'),
(23,'Kabupaten Manggarai Barat'),
(23,'Kabupaten Manggarai Timur'),
(23,'Kabupaten Nagekeo'),
(23,'Kabupaten Ngada'),
(23,'Kabupaten Rote Ndao'),
(23,'Kabupaten Sabu Raijua'),
(23,'Kabupaten Sikka'),
(23,'Kabupaten Sumba Barat'),
(23,'Kabupaten Sumba Barat Daya'),
(23,'Kabupaten Sumba Tengah'),
(23,'Kabupaten Sumba Timur'),
(23,'Kabupaten Timor Tengah Selatan'),
(23,'Kabupaten Timor Tengah Utara'),
(23,'Kota Kupang'),

-- 24. Papua
(24, 'Kabupaten Asmat'),
(24, 'Kabupaten Biak Numfor'),
(24, 'Kabupaten Boven Digoel'),
(24, 'Kabupaten Deiyai'),
(24, 'Kabupaten Dogiyai'),
(24, 'Kabupaten Intan Jaya'),
(24, 'Kabupaten Jayapura'),
(24, 'Kabupaten Jayawijaya'),
(24, 'Kabupaten Keerom'),
(24, 'Kabupaten Kepulauan Yapen'),
(24, 'Kabupaten Lanny Jaya'),
(24, 'Kabupaten Mamberamo Raya'),
(24, 'Kabupaten Mamberamo Tengah'),
(24, 'Kabupaten Mappi'),
(24, 'Kabupaten Merauke'),
(24, 'Kabupaten Mimika'),
(24, 'Kabupaten Nabire'),
(24, 'Kabupaten Nduga'),
(24, 'Kabupaten Paniai'),
(24, 'Kabupaten Pegunungan Bintang'),
(24, 'Kabupaten Puncak'),
(24, 'Kabupaten Puncak Jaya'),
(24, 'Kabupaten Sarmi'),
(24, 'Kabupaten Supiori'),
(24, 'Kabupaten Tolikara'),
(24, 'Kabupaten Waropen'),
(24, 'Kabupaten Yahukimo'),
(24, 'Kabupaten Yalimo'),
(24, 'Kota Jayapura'),

-- 25. Papua Barat
(25,'Kabupaten Fakfak'),
(25,'Kabupaten Kaimana'),
(25,'Kabupaten Manokwari'),
(25,'Kabupaten Manokwari Selatan'),
(25,'Kabupaten Maybrat'),
(25,'Kabupaten Pegunungan Arfak'),
(25,'Kabupaten Raja Ampat'),
(25,'Kabupaten Sorong'),
(25,'Kabupaten Sorong Selatan'),
(25,'Kabupaten Tambrauw'),
(25,'Kabupaten Teluk Bintuni'),
(25,'Kabupaten Teluk Wondama'),
(25,'Kota Sorong'),

-- 26. Papua Barat Daya
(26,'Kabupaten Maybrat'),
(26,'Kabupaten Raja Ampat'),
(26,'Kabupaten Sorong'),
(26,'Kabupaten Sorong Selatan'),
(26,'Kabupaten Tambrauw'),
(26,'Kota Sorong'),

-- 27. Papua Pegunungan
(27,'Kabupaten Lanny Jaya'),
(27,'Kabupaten Mamberamo Tengah'),
(27,'Kabupaten Mamberamo Raya'),
(27,'Kabupaten Jayawijaya'),
(27,'Kabupaten Nduga'),
(27,'Kabupaten Puncak'),
(27,'Kabupaten Puncak Jaya'),
(27,'Kota Jayapura'),

-- 28. Papua Selatan
(28,'Kabupaten Asmat'),
(28,'Kabupaten Boven Digoel'),
(28,'Kabupaten Mappi'),
(28,'Kabupaten Merauke'),

-- 29. Papua Tengah
(29,'Kabupaten Deiyai'),
(29,'Kabupaten Dogiyai'),
(29,'Kabupaten Intan Jaya'),
(29,'Kabupaten Mimika'),
(29,'Kabupaten Nabire'),
(29,'Kabupaten Paniai'),
(29,'Kabupaten Puncak'),
(29,'Kabupaten Puncak Jaya'),

-- 30. Riau
(30, 'Kabupaten Bengkalis'),
(30, 'Kabupaten Indragiri Hilir'),
(30, 'Kabupaten Indragiri Hulu'),
(30, 'Kabupaten Kampar'),
(30, 'Kabupaten Kepulauan Meranti'),
(30, 'Kabupaten Kuantan Singingi'),
(30, 'Kabupaten Pelalawan'),
(30, 'Kabupaten Rokan Hilir'),
(30, 'Kabupaten Rokan Hulu'),
(30, 'Kabupaten Siak'),
(30, 'Kota Dumai'),
(30, 'Kota Pekanbaru'),

-- 31. Sumatera Barat
(31,'Kabupaten Agam'),
(31,'Kabupaten Dharmasraya'),
(31,'Kabupaten Kepulauan Mentawai'),
(31,'Kabupaten Lima Puluh Kota'),
(31,'Kabupaten Padang Pariaman'),
(31,'Kabupaten Pasaman'),
(31,'Kabupaten Pasaman Barat'),
(31,'Kabupaten Pesisir Selatan'),
(31,'Kabupaten Sijunjung'),
(31,'Kabupaten Solok'),
(31,'Kabupaten Solok Selatan'),
(31,'Kabupaten Tanah Datar'),
(31,'Kota Bukittinggi'),
(31,'Kota Padang'),
(31,'Kota Padang Panjang'),
(31,'Kota Pariaman'),
(31,'Kota Payakumbuh'),
(31,'Kota Sawahlunto'),
(31,'Kota Solok'),

-- 32. Sumatera Selatan
(32, 'Kabupaten Banyuasin'),
(32, 'Kabupaten Empat Lawang'),
(32, 'Kabupaten Lahat'),
(32, 'Kabupaten Muara Enim'),
(32, 'Kabupaten Musi Banyuasin'),
(32, 'Kabupaten Musi Rawas'),
(32, 'Kabupaten Ogan Ilir'),
(32, 'Kabupaten Ogan Komering Ilir'),
(32, 'Kabupaten Ogan Komering Ulu'),
(32, 'Kabupaten Ogan Komering Ulu Selatan'),
(32, 'Kabupaten Ogan Komering Ulu Timur'),
(32, 'Kabupaten Pagar Alam'),
(32, 'Kabupaten Penukal Abab Lematang Ilir'),
(32, 'Kabupaten Prabumulih'),
(32, 'Kabupaten Rawas Ilir'),
(32, 'Kabupaten Rawas Ulu'),
(32, 'Kota Lubuklinggau'),
(32, 'Kota Palembang'),
(32, 'Kota Pagar Alam'),
(32, 'Kota Prabumulih'),
(32, 'Kota Sekayu'),

-- 33. Sumatera Utara
(33,'Kabupaten Asahan'),
(33,'Kabupaten Batu Bara'),
(33,'Kabupaten Dairi'),
(33,'Kabupaten Deli Serdang'),
(33,'Kabupaten Humbang Hasundutan'),
(33,'Kabupaten Karo'),
(33,'Kabupaten Labuhanbatu'),
(33,'Kabupaten Labuhanbatu Selatan'),
(33,'Kabupaten Labuhanbatu Utara'),
(33,'Kabupaten Langkat'),
(33,'Kabupaten Mandailing Natal'),
(33,'Kabupaten Nias'),
(33,'Kabupaten Nias Barat'),
(33,'Kabupaten Nias Selatan'),
(33,'Kabupaten Nias Utara'),
(33,'Kabupaten Padang Lawas'),
(33,'Kabupaten Padang Lawas Utara'),
(33,'Kabupaten Pakpak Bharat'),
(33,'Kabupaten Samosir'),
(33,'Kabupaten Serdang Bedagai'),
(33,'Kabupaten Simalungun'),
(33,'Kabupaten Tapanuli Selatan'),
(33,'Kabupaten Tapanuli Tengah'),
(33,'Kabupaten Tapanuli Utara'),
(33,'Kabupaten Toba Samosir'),
(33,'Kota Binjai'),
(33,'Kota Gunungsitoli'),
(33,'Kota Medan'),
(33,'Kota Padangsidimpuan'),
(33,'Kota Pematang Siantar'),
(33,'Kota Sibolga'),
(33,'Kota Tanjungbalai'),
(33,'Kota Tebing Tinggi'),

-- 34. Sulawesi Barat
(34, 'Kabupaten Majene'),
(34, 'Kabupaten Mamasa'),
(34, 'Kabupaten Mamuju'),
(34, 'Kabupaten Mamuju Tengah'),
(34, 'Kabupaten Pasangkayu'),
(34, 'Kabupaten Polewali Mandar'),
(34, 'Kota Mamuju'),

-- 35. Sulawesi Selatan
(35,'Kabupaten Bantaeng'),
(35,'Kabupaten Barru'),
(35,'Kabupaten Bone'),
(35,'Kabupaten Bulukumba'),
(35,'Kabupaten Enrekang'),
(35,'Kabupaten Gowa'),
(35,'Kabupaten Jeneponto'),
(35,'Kabupaten Kepulauan Selayar'),
(35,'Kabupaten Luwu'),
(35,'Kabupaten Luwu Timur'),
(35,'Kabupaten Luwu Utara'),
(35,'Kabupaten Maros'),
(35,'Kabupaten Pangkajene Dan Kepulauan'),
(35,'Kabupaten Pinrang'),
(35,'Kabupaten Sidenreng Rappang'),
(35,'Kabupaten Sinjai'),
(35,'Kabupaten Soppeng'),
(35,'Kabupaten Takalar'),
(35,'Kabupaten Tana Toraja'),
(35,'Kabupaten Toraja Utara'),
(35,'Kabupaten Wajo'),
(35,'Kota Makassar'),
(35,'Kota Parepare'),
(35,'Kota Palopo'),

-- 36. Sulawesi Tengah
(36,'Kabupaten Banggai'),
(36,'Kabupaten Banggai Kepulauan'),
(36,'Kabupaten Banggai laut'),
(36,'Kabupaten Buol'),
(36,'Kabupaten Donggala'),
(36,'Kabupaten Morowali'),
(36,'Kabupaten Morowali Utara'),
(36,'Kabupaten Parigi Moutong'),
(36,'Kabupaten Poso'),
(36,'Kabupaten Sigi'),
(36,'Kabupaten Tojo Una-Una'),
(36,'Kabupaten Tolitoli'),
(36,'Kota Palu'),

-- 37. Sulawesi Tenggara
(37,'Kabupaten Bombana'),
(37,'Kabupaten Buton'),
(37,'Kabupaten Buton Selatan'),
(37,'Kabupaten Buton Tengah'),
(37,'Kabupaten Buton Utara'),
(37,'Kabupaten Kolaka'),
(37,'Kabupaten Kolaka Timur'),
(37,'Kabupaten Kolaka Utara'),
(37,'Kabupaten Konawe'),
(37,'Kabupaten Konawe Kepulauan'),
(37,'Kabupaten Konawe Selatan'),
(37,'Kabupaten Konawe Utara'),
(37,'Kabupaten Muna'),
(37,'Kabupaten Muna Barat'),
(37,'Kabupaten Wakatobi'),
(37,'Kota Baubau'),
(37,'Kota Kendari'),

-- 38. Sulawesi Utara(1,'Kabupaten Bolaang Mongondow'),
(38,'Kabupaten Bolaang Mongondow Selatan'),
(38,'Kabupaten Bolaang Mongondow Timur'),
(38,'Kabupaten Bolaang Mongondow Utara'),
(38,'Kabupaten Minahasa'),
(38,'Kabupaten Minahasa Selatan'),
(38,'Kabupaten Minahasa Tenggara'),
(38,'Kabupaten Minahasa Utara'),
(38,'Kabupaten Siau Tagulandang Biaro'),
(38,'Kabupaten Kepulauan Sangihe'),
(38,'Kabupaten Kepulauan Talaud'),
(38,'Kabupaten Kota Bitung'),
(38,'Kabupaten Kota Kotamobagu'),
(38,'Kabupaten Kota Manado'),
(38,'Kabupaten Kota Tomohon');


CREATE TABLE kuisioner(
    alumni_id INT PRIMARY KEY,
    alamat VARCHAR(255) NOT NULL,
    provinsi_id INT NOT NULL,
    kabupaten_id INT NOT NULL,
    kode_pos VARCHAR(7) NOT NULL,
    nomor_hp VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    jenis_kelamin VARCHAR(10) NOT NULL,
    q13a VARCHAR(2),
    q14 VARCHAR(2),
    q14a VARCHAR(255),
    q15a VARCHAR(100),
    q15b VARCHAR(50),
    q15c VARCHAR(50),
    q16 VARCHAR(50),
    q17 VARCHAR(5),
    q18 VARCHAR(20),
    q19 TEXT,
    q20 VARCHAR(255),
    q21 VARCHAR(2),
    q22 VARCHAR(2),
    q23 VARCHAR(2),
    q24 VARCHAR(2),
    q25 VARCHAR(2),
    q26 VARCHAR(2),
    q27 VARCHAR(150),
    q28 VARCHAR(150),
    q29 VARCHAR(150),
    q30 VARCHAR(2),
    q31 VARCHAR(2),
    q32 VARCHAR(2),
    q33 VARCHAR(2),
    q34 VARCHAR(2),
    q35 VARCHAR(2),
    q36 VARCHAR(2),
    q37 VARCHAR(2),
    q38 VARCHAR(2),
    q39 VARCHAR(2),
    q39a TEXT,
    -- kuisoner 40
    q40a VARCHAR(2),
    q40b VARCHAR(2),
    q40c VARCHAR(2),
    q40d VARCHAR(2),
    q40e VARCHAR(2),
    q40f VARCHAR(2),
    -- kuisioner 41
    q41a VARCHAR(2),
    q41b VARCHAR(2),
    q41c VARCHAR(2),
    q41d VARCHAR(2),
    q41e VARCHAR(2),
    -- kuisioner 42
    q42a VARCHAR(2),
    q42b VARCHAR(2),
    q42c VARCHAR(2),
    q42d VARCHAR(2),
    q42e VARCHAR(2),
    q42f VARCHAR(2),
    q42g VARCHAR(2),
    q42h VARCHAR(2),
    q42i VARCHAR(2),
    q42j VARCHAR(2),
    q42k VARCHAR(2),
    -- kuisioner 43
    q43a VARCHAR(2),
    q43b VARCHAR(2),
    q43c VARCHAR(2),
    q43d VARCHAR(2),
    q43e VARCHAR(2),
    q43f VARCHAR(2),
    q43g VARCHAR(2),
    -- kuisioner 44
    q44a VARCHAR(2),
    q44b VARCHAR(2),
    q44c VARCHAR(2),
    q44d VARCHAR(2),
    q44e VARCHAR(2),
    q44f VARCHAR(2),
    q44g VARCHAR(2),
    q44h VARCHAR(2),
    q44i VARCHAR(2),
    q44j VARCHAR(2),
    q44k VARCHAR(2),
    q44l VARCHAR(2),
    q44m VARCHAR(2),
    q44n VARCHAR(2),
    q44o VARCHAR(2),
    q44p VARCHAR(2),
    q44q VARCHAR(2),
    q44r VARCHAR(2),
    -- kuisioner 45
    q45a VARCHAR(2),
    q45b VARCHAR(2),
    q45c VARCHAR(2),
    q45d VARCHAR(2),
    q45e VARCHAR(2),
    q45f VARCHAR(2),
    -- kuisioner 46
    q46a VARCHAR(2),
    q46b VARCHAR(2),
    q46c VARCHAR(2),
    q46d VARCHAR(2),
    q46e VARCHAR(2),
    q46f VARCHAR(2),
    q46g VARCHAR(2),
    q46h VARCHAR(2),
    q46i VARCHAR(2),
    q46j VARCHAR(2),
    q46k VARCHAR(2),
    q46l VARCHAR(2),
    q46m VARCHAR(2),
    q46n VARCHAR(2),
    q46o VARCHAR(2),
    q46p VARCHAR(2),
    q46q VARCHAR(2),
    q46r VARCHAR(2),
    -- kuisioner biasa
    q47 VARCHAR(2),
    q48 VARCHAR(2),
    q49 VARCHAR(2),
    q49a TEXT,
    q50 VARCHAR(2),
    q50a TEXT,
    FOREIGN KEY (alumni_id) REFERENCES alumni(id) ON DELETE CASCADE, -- Kunci asing mengacu pada tabel alumni
    FOREIGN KEY (provinsi_id) REFERENCES provinsi(id) ON DELETE CASCADE,
    FOREIGN KEY (kabupaten_id) REFERENCES kabupaten(id) ON DELETE CASCADE
)
